<?php

namespace GL\ProtocolloBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ClassificazioneRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClassificazioneRepository extends EntityRepository
{
}