<?php

namespace GL\ProtocolloBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * FascicoloRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FascicoloRepository extends EntityRepository
{
}