<?php

namespace GL\ProtocolloBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ProtocolloRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProtocolloRepository extends EntityRepository
{
}